# Generated by Django 2.2.5 on 2019-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0002_auto_20191005_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
