# Generated by Django 2.2.5 on 2019-10-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0003_member_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='celluser',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cell.Member'),
        ),
    ]
