# Generated by Django 2.2.5 on 2019-10-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0004_celluser_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellUser',
        ),
    ]
